console.log("Added App.js")
console.log("Checking Webhook Attempt 1")
console.log("Checking Webhook Attempt 2")
console.log("Checking Webhook Attempt 3")
console.log("Checking Webhook Attempt 4")
console.log("Checking Webhook Attempt 5 and Branch changing to `Master`")
console.log("Checking Webhook Attempt 6 and Branch changing to created `Master`")
